apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-sockets
  namespace: fast
data:
  HELLNET_ENVIRONMENT: Development
  HELLNET_PORT: '8080'
  HELLNET_TELEMETRY_ENDPOINT: http://alloy.observability.svc.cluster.local:4318
  KAFKA_BROKERS: redpanda.tools.svc.cluster.local:9093
  KAFKA_DEFAULT_SERIALIZER: avro
  KAFKA_SCHEMA_REGISTRY_PATH: none
  KAFKA_SCHEMA_REGISTRY_URL: http://redpanda.tools.svc.cluster.local:8081
  KAFKA_SCHEMA_SUBJECT_STRIP_PREFIX: br.com.hellnet.
  KAFKA_SECURITY_PROTOCOL: plaintext
  KAFKA_TOPIC_ORDER_ACCEPTED: br.com.hellnet.fast.order.accepted.v1
  KAFKA_TOPIC_ORDER_REQUESTED: br.com.hellnet.fast.order.requested.v1
  SOCKET_DRIVERS_NAMESPACE: /drivers
  SOCKET_RIDERS_NAMESPACE: /riders
